language: ruby

rvm:
  - 2.7

before_script:
  - psql -c 'create database gtbox_account_test;' -U postgres
  - rake db:migrate

before_install:
    - gem update --system
    - gem install bundler
    - nvm install 12
  
install:
  - yarn install
  - bundle install --jobs=3 --retry=3

services:
  - postgresql
