version: '3.7'
services:
  account:
    build:
      context: '.'
      dockerfile: Dockerfile.build
    entrypoint: ./bin/entrypoint
    environment:
      - GEM_HOME=/var/task/vendor/bundle/ruby/2.7.0
      - RAILS_ENV=${RAILS_ENV-development}
      - SAM_CLI_TELEMETRY=0
      - AWS_PROFILE=${AWS_PROFILE-default}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION-us-east-1}
      - CI=${CI}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
    volumes:
      - ${PWD}:/var/task
      - ${HOME}/.aws:/lamby/.aws
      - /var/run/docker.sock:/var/run/docker.sock
    user: "lamby"

  db:
    image: postgres:10
    volumes:
      - './tmp/db:/var/lib/postgresql/data'
