version: '3'
services:
  web:
    build:
      context: ../
      dockerfile: Dockerfile.dev
    command: sleep infinity
    environment:
      app_database_host: db
      RAILS_LOG_TO_STDOUT: 1
      RAILS_SERVE_STATIC_FILES: 1
    ports:
      - "80:80"
    expose:
      - "80"
    links:
      - db:db
    volumes:
      - ..:/src/gospeltoolbox/account

  db:
    image: postgres:10
    volumes:
      - ../tmp/db:/var/lib/postgresql/data
