# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 045cdf400bb23b7bf93e841c82d37bc6cb9c351d3a9bc311881ad4f1031ba427d72c243a6c4acd41adf1c029768794890d13fe56236c9ce9883e8809f4b726a6

test:
  secret_key_base: 228d4f55589cc22108a8b5e7bf0e608a0e615b00a6b61e535282a4d188e43d9b90810b98d8084734fb12c4eed3e1fdf9b801376639e88b20a79baa43756f8d25

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
